### ISSUE TITLE
Prioritize exact maches in ListDropdown filter

### ISSUE THREAD

**Issue by h3rmanj** [openshift/console#11114]
Hi!

It would be nice if the ListDropdown filter would prioritize exact matches.

For example, in Create RoleBinding UI, when I search the Role list for `edit`, I get these results;
![image](https://user-images.githubusercontent.com/11387548/156143675-3d10faeb-77bb-46be-95d2-760eded15d2c.png)

And I actually have to scroll down to find the role named `edit`.
![image](https://user-images.githubusercontent.com/11387548/156143962-15969316-271e-4469-a5a9-c0ec8f5f6632.png)

I'm not sure how this would be implemented though. I found `fuzzysearch` was used for dropdown filtering, which doesn't really support this. It might be possible to do a sort or find on the fuzzysearch results, where all we look for is an exact match to show first?

**Comment by spadgett** [comment]
We could look at switching to a library like https://github.com/farzher/fuzzysort to give a weighted sort.

cc @alimobrem @jhadvig

**Comment by TheRealJon** [comment]
@h3rmanj Thanks for your feedback! Apologies for the delay, but GitHub is not our usual method for tracking issues in this repo. For feature requests, we recommend you follow the guidelines found [here](https://access.redhat.com/solutions/73513), or if you feel this is a bug, you can open a Jira issue [here](https://issues.redhat.com/secure/CreateIssueDetails!init.jspa?pid=12332330&issuetype=1&components=12367696). If you do request the feature or open a bug, please let me know so that we can close this and link to the appropriate Jira issue. I'm going to take the `lifecycle/frozen` label off of this issue so that it will be closed automatically if there is no further activity.
