### ISSUE TITLE
PROJECT_NAVIGATION canI fails on group permissions

### ISSUE THREAD

**Issue by Pectojin** [openshift/console#1120]
**Issue**
The `Resources -> Membership` navigation item disappears on the project page if the user is not directly assigned to a role that provides `verb: list, resource: rolebinding`.

In our cluster we assign permissions through group membership, so my users have read access on rolebindings through a group.

I was able to work around this by overwriting the canI dict, but it would be nice if the console could resolve group permissions.

**Workaround**
In case anyone needs a workaround for this, in [console customization](https://docs.openshift.com/container-platform/3.11/install_config/web_console_customization.html) I've put the below to overwrite the check.
`window.OPENSHIFT_CONSTANTS.PROJECT_NAVIGATION.find(item => item.label == "Resources").secondaryNavSections[0].items.find(item => item.label == "Membership").canI = null`

**Comment by spadgett** [comment]
I'm a little uncertain why this would be a problem since the console performs a `SelfSubjectRulesReview`, which should account for group permissions.

It might be that we're requesting access to `rolebinding` and not `rbac.authorization.k8s.io/rolebinding`. If you switch the `canI` stanza to following, does it work?

```js
{
  group: 'rbac.authorization.k8s.io',
  resource: 'rolebindings',
  verb: 'list'
}
```

(Note that this issue should go in the openshift/origin-web-console. This repo is for the 4.0 console, which is a different code base.)

**Comment by spadgett** [comment]
/close

Fixed by https://github.com/openshift/origin-web-console/pull/3110
