### ISSUE TITLE
Enable filtering for k8sResourcePrefix x-descriptor

### ISSUE THREAD

**Issue by ivandov** [openshift/console#11747]
When using the [`k8sResourcePrefix`](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#3-k8sResourcePrefix) x-descriptor, the rendered dropdown in the console UI will display all resources that match this prefix. 

However, in some scenarios, I'd like to only display a subset of the resources based on some filtering mechanism. 

I'd imagine this "filter" could match the syntax and capabilities of the label selector CLI flag 
```
-l, --selector='': Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)
```

Therefore functioning similarly as `oc get <resource> -l <filter>`. 

Additional filtering mechanisms could be possible beyond a simple label-based filter, but, in my scenario a label filter would sufficient.

**Comment by spadgett** [comment]
Hi, @ivandov. As you've found, this isn't possible today. We'll consider it as a new feature.

cc @alimobrem

**Comment by ivandov** [comment]
Thanks @spadgett - Is there some other internal tracking mechanism that you all use to prioritize enhancement requests? I believe there was a Jira environment that's used? Any links I should be following?

This request is needed for our product's desired user experience, and without it, we're potentially needing to take a path that has significantly more complexity using OCP Dynamic Plugins. While I'm excited about the possibilities of Dynamic Plugins, I'd like to avoid having to use that for what should be a relatively simple addition. 

Would this be something that you would consider a PR in this repo for as well?

**Comment by spadgett** [comment]
Hi, @ivandov. The RFE process for OpenShift (and other Red Hat products) is described here: https://access.redhat.com/solutions/73513. Having said that, we always welcome PRs!

We've been focused on dynamic plugins for more advanced customizations, although I understand the appeal of the simple, declarative approach.

An optional label selector makes sense here. We'd need to find a way to encode it into the descriptor somehow. cc @TheRealJon @jhadvig

**Comment by eduardo-at** [comment]
Based on the above discussion and the need for this feature I've implemented resource filtering by combining spec descriptors with standard Kubernetes label selector syntax, both equity-based and set-based as explained here: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

As means to encode it I chose to follow the https://en.wikipedia.org/wiki/Uniform_Resource_Identifier standard and since the label selector is a query, the character '?' seemed proper to begin the query and the character '+' to encode spaces.

So the syntax `urn:alm:descriptor:io.kubernetes:ServiceAccount?label!=test,level=production` would only list the ServiceAccounts that match the label selector.

Therefore I'll reopen this issue, create a branch topic on my fork and submit a PR referencing this issue.
/reopen

**Comment by ivandov** [comment]
@spadgett - @eduardo-at is part of my team and this is something that our product's design would benefit from. Out of curiosity, if his PR makes it past review and is merged into this upstream repo, what's the rollout strategy to have the enhancements available in OpenShift releases? 

Does the enhancement only make it into new OCP versions, or updates to existing streams? We'd be wanting to target support for 4.10 and above.

**Comment by TheRealJon** [comment]
Migrated to Jira: https://issues.redhat.com/browse/CONSOLE-3622
