### ISSUE TITLE
Question: urn:alm:descriptor:com.tectonic.ui:select: Value and Label support

### ISSUE THREAD

**Issue by manstis** [openshift/console#13691]
Hello, 

I couldn't find anywhere else to ask.

This is a question (not an issue) about OLM `ClusterServiceVersion` configuration.

Specifically, `urn:alm:descriptor:com.tectonic.ui:select` and how I can define `value` and `label`.

[Examples](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md?plain=1#L538-L569) only show use of a value that is used in both the UI and to populate the related CRD.

However the [source code](https://github.com/openshift/console/blob/master/frontend/packages/console-shared/src/components/dynamic-form/widgets.tsx#L196) suggests both value and label are supported.

Looking for pointers/suggestions/etc.

**Comment by logonoff** [comment]
hey! 

not speaking on behalf of Red Hat, but the [OKD discussions](https://github.com/okd-project/okd/discussions) or [#openshift-users on Kubernetes Slack](https://communityinviter.com/apps/kubernetes/community) might be a better place to ask questions relating to OpenShift.

alternatively, since you have a Red Hat OpenShift subscription, you could always [open a case](https://access.redhat.com/support/cases/new)

cheers :smile:

/close

**Comment by logonoff** [comment]
/open

@jhadvig pinging in hopes of an answer :p

**Comment by logonoff** [comment]
/reopen

@jhadvig pinging in hopes of an answer :p
