### ISSUE TITLE
Displayed time does not respect locale format

### ISSUE THREAD

**Issue by Jiehong** [openshift/console#1435]
Hello,

Date/Time in the console UI is displayed in US locale format by default, and does not take into account the browser locale.

For example, my browser's language is set to `English (UK)`, yet I see the following:

![image](https://user-images.githubusercontent.com/1061229/56214741-bae0d580-605e-11e9-88ed-f3650fe5dca9.png)

Which is clearly not UK, but US.

In my case, I'd expect something such as `9/4/2019 15:14:39` (not the 24h format).

**Comment by spadgett** [comment]
This is a screenshot from previous 3.x console tracked at openshift/origin-web-console. However, the 4.x console also has a similar problem since it doesn't generate times for the user's locale.

https://github.com/openshift/console/blob/master/frontend/public/components/utils/timestamp.jsx#L72-L104

/kind bug

**Comment by spadgett** [comment]
I believe this will be addressed in 4.x as part of #6194. @rebeccaalpert can you confirm?

**Comment by rebeccaalpert** [comment]
@spadgett - We're only using the "en" locale right now for English rather than breaking it down to US, UK, etc., but we could specify more granular "en" locale times by adding additional locales to i18next.

For English, it looks like there's:
- English - Australia | en | en-au 
- English - Belize | en | en-bz
- English - Canada | en | en-ca 
- English - Caribbean | en | en-cb
- English - Great Britain | en | en-gb 
- English - India | en | en-in
- English - Ireland | en | en-ie
- English - Jamaica | en | en-jm
- English - New Zealand | en | en-nz
- English - Philippines | en | en-ph
- English - Southern Africa | en | en-za
- English - Trinidad | en | en-tt
- English - United States | en | en-us
- English - Zimbabwe | en

I can look into which ones besides the UK use different time formats and add those to the PR if you want @spadgett. I'm assuming we won't be localizing OpenShift for UK English, etc. aside from dates in this release. (There's different spellings, etc.)

**Comment by spadgett** [comment]
@rebeccaalpert We should look at supporting at least some of these locales for date and number formats.

**Comment by rebeccaalpert** [comment]
We've added English (UK) timestamps as of 4.7, but have not addressed other English timestamp formats yet.

**Comment by rebeccaalpert** [comment]
This should be all set as of 4.8.
