### ISSUE TITLE
RFE - centralize information about route & registry in About page

### ISSUE THREAD

**Issue by jupierce** [openshift/console#1874]
In OpenShift 3.x, the About page displayed information about routes, DNS, and how to access the internal registry. In OpenShift 4, this information is available, but distributed around the UI. Personnel fielding user issues with starter clusters are interested in having a single link they can share to get users on track and would benefit from this information being restored.

Opening here so that stakeholders can discuss. cc: @jiri-fiala @wgordon17

**Comment by wgordon17** [comment]
Here's a screenshot of the information that we're providing in v3:

![image](https://user-images.githubusercontent.com/22222756/60457957-59ff7d00-9c0b-11e9-938d-97e6ab7257d2.png)

**Comment by spadgett** [comment]
For context, here are the 4.x implementations: #1431 and #1491 

This actually seems more hidden to me than showing up directly on the resource pages themselves. If you have a route, you can see the canonical router hostname for that route. If you have an image stream, you can see specific commands for pushing to and pulling from that image stream.

From an implementation standpoint, this is tricky because we don't know the router hostname without actually have a route resource.

I'm not sure if this will work in environments when there are multiple routers since there isn't a single router hostname as I understand. cc @ironcladlou

**Comment by spadgett** [comment]
We could conceivably get the public registry hostname from one of the image streams in the `openshift` namespace and show it in the about dialog. Router canonical hostname is more difficult.
