### ISSUE TITLE
Visual issues with new dashboards

### ISSUE THREAD

**Issue by spadgett** [openshift/console#2037]
cc @rawagner @lizsurette @rhamilto 

![Screen Shot 2019-07-15 at 5 42 03 PM](https://user-images.githubusercontent.com/1167259/61251538-bb097380-a728-11e9-9237-4136e4bc5e02.png)

<img width="583" alt="Red Hat OpenShift Container Platform 2019-07-15 17-48-29" src="https://user-images.githubusercontent.com/1167259/61251608-f60ba700-a728-11e9-8538-752e6079b023.png">

**Comment by spadgett** [comment]
The tooltips under "Details" are a weird when not needed. For instance, "AWS" has a tooltip. They also use a different tooltip style than the rest of console.

**Comment by lizsurette** [comment]
@spadgett Thanks for calling these out so clearly! @andybraren @mceledonia - Mind working with @rawagner and others to help with suggestions around these bugs where we can help? I think generally it's about confirming icon sizes and such :)

**Comment by andybraren** [comment]
Draft PR #2041 attempts to address most of these except the Utilization card's text cutting off and the differing icon sizes in the Inventory card. Any ideas on those @matthewcarleton?

> (Details)
> Should we use Cluster ID instead?
> Tooltip is cut off when open

Changing to Cluster ID makes sense. I suggest we remove the tooltips entirely @rawagner and let the text wrap, which is what our future dashboard designs will do. Text wrapping is included in the PR.

![image](https://user-images.githubusercontent.com/9122899/61264730-8cf15700-a75b-11e9-9d1a-acff50c4c265.png)

> (Health) Icons are different sizes

PR improves this, although icon fonts are still a bit weird.

![image](https://user-images.githubusercontent.com/9122899/61263368-92986e00-a756-11e9-88df-88cd3da7842d.png)

> (Events)
> Weird leading hyphens
> Text is cut off

Hyphens are a bug @rawagner. Text is fixed in the PR, along with some padding above the diving line between events.

![image](https://user-images.githubusercontent.com/9122899/61265548-a516a580-a75e-11e9-84ac-a515467368ab.png)

> (Capacity)
> Text is so small it's barely legible

Fixed in PR.

![image](https://user-images.githubusercontent.com/9122899/61265578-c7102800-a75e-11e9-89d7-a61fe44689b0.png)

> (Utilization)
> Almost the same, but slightly different font sizes

Fixed in PR.

![image](https://user-images.githubusercontent.com/9122899/61265791-f1aeb080-a75f-11e9-8a57-1bb91adb8b6f.png)

**Comment by rawagner** [comment]
@andybraren that was fast ! :) 
Here is a PR for fixing utilization axis cut off https://github.com/openshift/console/pull/2044

**Comment by rawagner** [comment]
> Hyphens seem like a bug, right @rawagner? Text is fixed in the PR, along with some padding above the divider line between events.

@andybraren 
that happens happens when the card is smaller and text `- <number> times in the last.. ` flows to new line 

here's how it looks with wider events card

![events-hyphen](https://user-images.githubusercontent.com/2078045/61277077-aa511000-a7b1-11e9-9550-4180ee59bb2f.png)

any idea how to fix that with some clever css ?

**Comment by spadgett** [comment]
I'd expect the text to break at word boundaries instead of wrapping together, but we might want to just pull it down to the next line if there's not enough room.

In general, I feel like there's a bit too much content in this card. If this is cluster-wide events, there could be a lot, and this is a small space. They could be moving fast in an active cluster. Maybe we should link out to the full events page?

**Comment by spadgett** [comment]
Thanks for the quick turnaround on these items! The dashboards have a ton of potential, and I realize we're iterating quickly here. I just want it to feel really polished when we ship 👍

**Comment by andybraren** [comment]
> any idea how to fix that with some clever css ?

Hmm... I suppose just wrapping is fine for now at small sizes. I've updated my PR to tweak the HTML/CSS of the timestamp line a bit (hopefully correctly).

![image](https://user-images.githubusercontent.com/9122899/61311738-f6f21680-a7c4-11e9-9adc-f4a46f0bda1c.png)

> In general, I feel like there's a bit too much content in this card.

We agree, and the future "Activity" card design that will eventually replace this Events card doesn't include "# times in the last X hours" or "Generated by X" at all.

Any objections to removing the "Generated from X" line from this card @spadgett @rawagner? Or maybe even the "# times" instead? Not sure which is more important to the user. The link to the Events page is definitely something we'd like to have though. Here was the original design for reference:

![image](https://user-images.githubusercontent.com/9122899/61310457-54d12f00-a7c2-11e9-8c23-0d37ca6cb3e9.png)

**Comment by rawagner** [comment]
@spadgett @andybraren here is a [PR for Events card ](https://github.com/openshift/console/pull/2063). Added View all link and removed `# times in the last X hours` and `Generated from`.
