### ISSUE TITLE
Update webdriver to match chrome version 76

### ISSUE THREAD

**Issue by gouyang** [openshift/console#2230]
Chrome 76 is available on Fedora 30 now, run test meet error "session not created: Chrome version must be between 71 and 75". It seems need to update webdriver-manager version to webdriver-manager-12.1.5.

**Comment by spadgett** [comment]
Working on this in #2320. The problem is that 76 is not the stable version in our console builder image, so it will break CI. It will also break the release-x.y branches. 

We need to come up with a way of dealing with this going forward as this will happen with every major chrome release now as chromedriver now only works for a specific major version of chrome.
