### ISSUE TITLE
Webpack isn't treeshaking library bundles

### ISSUE THREAD

**Issue by redallen** [openshift/console#2251]
With only [babel-loader] pointed at an `entry: index.js`, Webpack will treeshake harmony imports like `import { Button } from 'patternfly-react';` and not include the entirety of the `patternfly-react` project in it's bundle like it is currently:

![image](https://user-images.githubusercontent.com/47335686/62389963-2a57d380-b52f-11e9-81fc-5685864387af.png)

As a few examples, `patternfly-react`'s Wizard is included, along with `@patternfly/react-core`'s Text component.

Really, we should expect a bundle more like:
![image (2)](https://user-images.githubusercontent.com/47335686/62390265-da2d4100-b52f-11e9-8d26-a7dd32729a7c.png)

That doesn't include these components.

This will require removing the two `require('patternfly-react').then(m => m.Component)` in the project as well, since that forces Webpack to bundle the entire module.

**Comment by spadgett** [comment]
https://jira.coreos.com/browse/CONSOLE-1651

**Comment by spadgett** [comment]
I believe this is specific to the kubevirt plugin, likely kubevirt-web-ui-components. All of the PF3 components drop out of the main vendor bundle when disabling the kubevirt plugin.

cc @vojtechszocs 

Current master:

![Screen Shot 2019-08-16 at 2 41 17 PM](https://user-images.githubusercontent.com/1167259/63190332-036fc600-c034-11e9-9bb7-6cf2eef025f1.png)

With kubevirt plugin disabled:

![Screen Shot 2019-08-16 at 2 41 28 PM](https://user-images.githubusercontent.com/1167259/63190350-0cf92e00-c034-11e9-8744-0cb0a2ce3dd0.png)

**Comment by spadgett** [comment]
@dgutride fyi

**Comment by spadgett** [comment]
@mareklibra fyi

**Comment by redallen** [comment]
Correct, it is due to `kubevirt-web-ui-components`. That's why I went upstream to provide esm exports for it, and am now using them in #2232 .

**Comment by vojtechszocs** [comment]
@spadgett @redallen @mareklibra @jelkosz 

> Correct, it is due to `kubevirt-web-ui-components`.

This ^^ dependency was added due to migrating code from [kubevirt/web-ui](https://github.com/kubevirt/web-ui) fork to Console monorepo, impacting following packages:
- `frontend/packages/kubevirt-plugin`
- `frontend/packages/console-shared`

After 4.2 gets released and `master` branch re-opens for development, the KubeVirt group should dedicate some sprints to migrating `kubevirt-web-ui-components` code over to Console monorepo, resulting in eventual removal of this dependency as well as the fork itself.

As a result, any `kubevirt-xxx` chunks (as shown in #2394) should become smaller. The whole dependency sub-tree starting at `kubevirt-web-ui-components` should be cut off entirely.

**Comment by spadgett** [comment]
Fixed by the following PRs:

#2372
#2383
#2595

/close
