### ISSUE TITLE
Logging into console will use the project from previous session

### ISSUE THREAD

**Issue by jhadvig** [openshift/console#25]
When logging out from the console as userA, using projectA and logging back as userB, projectA will be set a default project for userB to use.

**Comment by spadgett** [comment]
This is working as intended. We don't currently have the projects list when the default is set, and a project always needs to be selected. The alternative is to use project `default` as the default, which most users can't see.

At some point, we might pick an item from your projects list, but that's not a simple change.

Since we've added a first time user experience when you don't have projects in #185, this problem is less severe.

**Comment by spadgett** [comment]
Since this issue was opened, we've improved the first-time user experience. You're shown the projects list when first logging in, and we added an empty state message to other views in #185. There are still some edge cases where you can see the 403 message, but on balance, I think the current experience is reasonable.

/close
