### ISSUE TITLE
Fix for showing decimal values in AreaGraph's Y-axis

### ISSUE THREAD

**Issue by bipuladh** [openshift/console#2569]
This issue refers to [https://github.com/openshift/console/pull/2296](2296) I am trying to come up with a solution for showing integers on the y-axis instead of floating-point values as discussed on PR 2296(link above). I have found few ways to implement a fix for the issue which is as follows:

1) Round all the values inside the humanize function. It will allow us to come up with clean rounded values but we will lose precision in the graph too.

2) Provide custom tick values. These custom tick values are generated using modular arithmetic so that the end values do not create fractional values. The tick points are generated using percentiles.

Very rough implementation ideas...
```
const adjust = (value) =>{
  const level = bestLevel(value);
  const adjusted = adjustValues(value, level);
  return adjusted * ( 1024 ** level )
}
const adjustValues = ( value, level, initial = 0 ) => {
  if (level == initial){
    return value;
  }
  else{
    let diff = value % 1024;
    value -= diff;
    return adjustValues( value / 1024, level, initial + 1);
  } 
}
```
Ticks being generated as follows(Very rough implementation. Need to work on the statistical part introducing calculations of percentiles/quartiles):
```
  const avg:number = sum / _.size(yData);
  let ticks:number[]= [ 3 * avg / 2 ,
                    avg,
                    avg / 2, ]
  
```

**Comment by bipuladh** [comment]
@cloudbehl ?

**Comment by spadgett** [comment]
cc @TheRealJon 
/kind feature

**Comment by bipuladh** [comment]
I have performed more testing on this issue with various solutions. The reason why victory shows fractions right now in the main dashboard is that we are converting the bytes to appropriate power in the following manner `tickFormat={tick => humanize(tick).string} ` in the area graph implementation.
What we can do is convert all the data points to appropriate power beforehand and pass it to the area graph. Doing that results in better scales.
The other method I have found is we let it remain as it is/or convert before but come up with the scale on our own. I did a rough implementation of it, improving on the above solution to improve on the differences.
The 3 different charts are as follows:
a) Current Situation
![current_impl](https://user-images.githubusercontent.com/54092533/64610477-f3f25b80-d3ec-11e9-8a83-cff85a8fa436.png)
b) Letting it handle tick generation( but pre-converting it to the appropriate level)
![auto generate](https://user-images.githubusercontent.com/54092533/64610527-0a001c00-d3ed-11e9-929f-7c4c441befc9.png)
c)My custom range handling(added more logic than above but right now more focused on bytes):
![my_impl](https://user-images.githubusercontent.com/54092533/64610594-2f8d2580-d3ed-11e9-81ce-9d78fdfa8062.png)

**Comment by vojtechszocs** [comment]
@andybraren What are your thoughts on points raised in Jon's comment above?

Assuming all the vertical (Y axis) ticks use `GiB` unit, a tooltip for e.g. `0.1 GiB` data point should be down-scaled to show `100 MiB`, correct?

Do we want to render the same-unit ticks, e.g. only`GiB` regardless of the actual values, or adapt (down- or up-scale) them like the following?

> if we have a data set that spans from 0 to 2 GiB, and we want tick labels every .5 GiB, will the first label say 500 MiB instead of .5 GiB

**Comment by bipuladh** [comment]
https://github.com/openshift/console/pull/2937/files

**Comment by andybraren** [comment]
@vojtechszocs @TheRealJon @bipuladh

I chatted about this with some other folks and we quickly agreed that the y-axis tick marks should always have the same unit label, so always `GiB` or always `TiB` depending on the largest possible value:

`1 TiB, 0.5 TiB, 0 TiB`

Since the tooltip should match the value shown in the Utilization card, I mocked up a comparison of what it would be like if the measurements on the left-hand side downscaled or always stayed the same:

![labels-changeroo-comparison](https://user-images.githubusercontent.com/9122899/66688128-555b5380-ec53-11e9-8099-d5ddc1148e12.png)

Comparing the two approaches, the granularity that downscaling provides seems important enough to make the conversion worth doing. In some cases not being able to see the extra `+/- 49 XiB` that gets rounded away could make capacity planning harder, especially as we start introducing more quota-related features in the future.

Does this seem reasonable?
