### ISSUE TITLE
Improve resource search in web console

### ISSUE THREAD

**Issue by startxfr** [openshift/console#4173]
Hi all,

In OCP 4.3 and previous versions, there is no equivalent of the `oc get all -l xx=yyy` search request within the web console.
In the search menu, we can search only a defined resource, but not all resources. Is it possible to add an all option to the resource kind dropdown list ?
If request is to huge to perform when no filter is apply, perhaps adding the all option could be suggested only when a filter is apply (like app=xx or version=x.x.x).

**Comment by spadgett** [comment]
#3875 adds the ability to search for multiple resources at once. You can bookmark these queries for reuse. Does this meet your needs?

Note that `all` on the CLI is not really all resources, but a small subset of important resources. We might consider adding an option to the resources dropdown that gives you the same set of resources.

/kind feature
cc @beanh66 @bmignano

**Comment by spadgett** [comment]
Fixed by #3875 which allows you to query multiple resources with an optional label filter.

We don't plan to add "All" since in a typical OpenShift cluster there are something like 100 resources. Console has to make separate requests for every resource. This does not scale when watching all resources in all namespaces.

/close
