### ISSUE TITLE
GitHub IDP(s) "authentication error" when already logged as wrong github user

### ISSUE THREAD

**Issue by cben** [openshift/console#4620]
[initially seen when opening console via cloud.redhat.com/openshift — https://issues.redhat.com/browse/SDA-1786 — but I believe independent]

Steps to Reproduce:
1. Add two Github IDPs on a cluster as bellow:

    Github user | organization | IDP name
    -- | -- | --
    user1 | org1 | myidp1
    user2 | org2 | myidp2

2. Open openshift console, login via myidp1 -> login to github as user1
3. Log out from openshift console
4. Try to login to console via myidp2
5. Open console in incognito window, try to login via myidp2

Actual results:
2. It succeed to login with myidp1 -> user1.
4. It fails to login with myidp2. The error message is "An authentication error occurred."
    The log shows (but console user doesn't see this explanation):
    ```
    # oc logs oauth-openshift-76cbc74664-7v8vp -n openshift-authentication | grep error
    E0103 05:33:32.498604       1 errorpage.go:26] AuthenticationError: User user1 is not a member of any allowed organizations [org2] (user is a member of [])
    ```
5. In incognito window, it succeed to login with myidp2 -> user2.

Expected results:
- [ ] Console should show explanation why you're not authenticated (which github user you are, which organizations/teams are authorized for this IDP).
- [ ] Console should give you a way to login with another github user, e.g. show a link to https://github.com/logout near the error message.

I suspect (untested) that similar scenario can happen with a single IDP, if you're already logged into github as an unrelated user.

**Comment by spadgett** [comment]
cc @stlaz

**Comment by stlaz** [comment]
/remove-lifecycle stale
I only noticed this issue now.

The problem is that you're already logged in to GitHub so when you attempt to login to myidp2, it reaches GitHub where you already have an active session as user1, so that is kept.

A solution would be to add a logout redirect URI to our config (needs RFE) so that console might attempt to close your GitHub session for you. In that case though, you would have to re-login to GitHub after console logout if you wanted to reach any other application that uses OpenShift OAuth to grant you access to it (like grafana, prometheus). And, similarly, you couldn't be logged in to GitHub as user1 prior to accessing any of the OpenShift services if you wanted to use myidp2...
