### ISSUE TITLE
How to Get Node Metrics on Native Kubernetes Cluster?

### ISSUE THREAD

**Issue by ryanelian** [openshift/console#4820]
Continuing discussion from https://github.com/openshift/console/issues/1377 albeit different topic hence different thread.

---

### Problem Description

The pages `/dashboards` and Compute Nodes (`/k8s/cluster/nodes`) unfortunately are partially-working in a native Kubernetes cluster (kubeadm 1.17.4)

I wonder what should be done to achieve complete functionality on those pages? Are there additional metric sidecar pods / services which I should deploy?

---

### Screenshots

![image](https://user-images.githubusercontent.com/8892187/77596014-6233e100-6f2d-11ea-8088-c6082bf8f4c7.png)

![image](https://user-images.githubusercontent.com/8892187/77596359-5e548e80-6f2e-11ea-991f-c2d4ef8a3473.png)

![image](https://user-images.githubusercontent.com/8892187/77596076-84c5fa00-6f2d-11ea-91b1-903dfc7cd5b5.png)

![image](https://user-images.githubusercontent.com/8892187/77596086-8db6cb80-6f2d-11ea-9d8d-e74d78999831.png)

**Comment by spadgett** [comment]
It will probably take a code change.

Right now, the console backend proxies to Prometheus and Alertmanager. We assume the OpenShift monitoring stack is running in the `openshift-monitoring` namespace and hard-code several services since they're at well-known locations:

https://github.com/openshift/console/blob/master/cmd/bridge/main.go#L37-L51

We'd need some way to make this configurable for native k8s.

**Comment by ryanelian** [comment]
> Right now, the console backend proxies to Prometheus and Alertmanager. 

That is convenient. I am running Prometheus using prometheus-operator Helm chart: 

https://github.com/coreos/prometheus-operator

https://github.com/helm/charts/tree/master/stable/prometheus-operator

I wonder if the Console is compatible with prometheus-operator metrics.
