### ISSUE TITLE
UI rendering the complete CRD instead of just name

### ISSUE THREAD

**Issue by prafull11** [openshift/console#4962]
I have two CRD's named **application** and **backup** in which we have to provide application name in the backup CR.

User just needs to provide the application CR name which he want to link to the backup CR and we find the  proper object reference and mutate it to the backup CR. However in the UI it is asking for all the information from the use. I just want that UI don't render all the fields of the application CRD. (attached snapshot). I want this Application not to be rendered. I have not mentioned this spec.application in spec descriptors but still UI is rendering on it.

![Screenshot from 2020-04-08 11-55-27](https://user-images.githubusercontent.com/56869150/78751465-ece5f880-798f-11ea-9a0c-a470d120d090.png)

**Comment by tlwu2013** [comment]
Hi @prafull11 ,

Want to reply here as well in addition to the separate email thread.
This is about some Operand's fields show up on the creation form but you want to hide them instead.

It's because OCP console also generates fields for Operand's creation form from its OpenAPI Schema in the CRD yaml in addition to the fields from the specDescriptors.

We've planned to have "a new specDescriptor to **hide**/**exclude** fields in the schema from being shown on the form UI”.
This is currently targeting the OCP 4.6 release.

**Comment by spadgett** [comment]
We've implemented a hidden spec descriptor in #5094. Let us know if this meets your needs.

/close
