### ISSUE TITLE
Error "Required value" for field "metadata.namespace"

### ISSUE THREAD

**Issue by gouyang** [openshift/console#581]
After apply kubevirt-web-ui [1] to ocp cluster, it could be able to create virtual machine in http://kubevirt-web-ui-kweb-ui.cloudapps.example.com. However, create a virtual machine from a typical yaml [2] file is failed because of such an error `Error "Required value" for field "metadata.namespace"`.

[1] https://github.com/kubevirt/web-ui
[2] https://raw.githubusercontent.com/kubevirt/kubevirt/master/cluster/examples/vm-cirros.yaml

Additional notes: 
By adding the namespace to the VM yaml, then create it works.

**Comment by gouyang** [comment]
> Also the first link refers to a repo, not sure why though.

I know it's a bit confused, because the yaml of kubevirt-web-ui is not existed anywhere, and it's from kubevirt/web-ui, so I put the link there.

**Comment by gouyang** [comment]
> So the Virtual Machine CRD is namespace scoped, so the namespace has to be supplied.

Copying a word from cnv-devel:
```
When running the YAML on the command like (kubectl create -f) the namespace is interpreted based on what the client is currently pointed at, shouldn't the same be true in the UI if In the project dropdown I do already have a project selected?
```

**Comment by jhadvig** [comment]
So in the admin console, the object that is being created from YAML(JSON) is expected to contain the namespace info.
ATM we are creating resource based on if YAML(JSON). If we would want to provide this kind of logic we would need to check when submitting the resource for create, if it's namespaced and if so modify the YAML accordingly. Also in case of CRD's it can get bit more tricky since you will need to get the model first. Also admin can have `all projects` picked,then we have to assume and default to a particular namespace (currently `default` ns).

@spadgett thoughts?
