### ISSUE TITLE
Add ability to hide older apiVersions in a CSV to avoid extra CRD tabs in the OLM UI

### ISSUE THREAD

**Issue by aharbis** [openshift/console#6602]
We recently added a new `apiVersion` to our operator so our `ClusterServiceVersion` provides metadata for both `v1beta1` and `v1beta2` CRDs. On OCP 4.5 this leads to some interesting (and undesireable) behavior in the Operator UI.

In our `v1beta1` API group, we have a single CRD: `DataPowerService`.
In our `v1beta2` API group, we have two CRDs: `DataPowerService` and `DataPowerMonitor`.

In the UI, there are two tabs rendered for `DataPowerService`, one for each API version.

![image](https://user-images.githubusercontent.com/20443310/92971084-cdc32980-f44d-11ea-9a7d-a5177eaa6e47.png)

This is undesirable, because `v1beta2` is our stored version. We don't really want users creating `v1beta1` CRs, and if they do they'll be converted to `v1beta2` and persisted at that version.

It would be ideal if we could (through CSV metadata hopefully) disable certain `apiVersions` from showing in the UI. Our operator still of course needs to know about the older versions, and the `DataPowerService` CRD itself does need to include both versioned schemas to support conversion etc., but there's no reason (in my opinion) for there to be a `v1beta1` CRD tab in the UI.

**Comment by spadgett** [comment]
cc @TheRealJon @tlwu2013 

Do you guys know if this is possible with the internal resource annotation?

**Comment by TheRealJon** [comment]
Normally, yes we could hide a provided API and the corresponding instance list tab using the `'operators.operatorframework.io/internal-objects'` annotation. But, this would be an interesting case because that annotation only accepts a CRD name. So, if we add the DataPowerService to it, I believe all of the provided API cards and instance tabs would be hidden, not just a specific API version. We would need to add the ability to provide API version along with CRD name in that annotation in order to support hiding only a specific version. That or we add some other logic where we only show the latest API version of each CRD.

**Comment by spadgett** [comment]
We should probably only show one API version for each kind/group. We can use the utility added in #5355 to find the preferred version.

**Comment by TheRealJon** [comment]
This is now being tracked in bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1888036
Closing.
