### ISSUE TITLE
Reduce number of clicks in developer/admin dropdown

### ISSUE THREAD

**Issue by WillNilges** [openshift/console#6947]
Right now, I have to open the developer/admin dropdown and then click the mode in order to change. I think it'd make more sense if you could toggle the modes with a slider or something, since there's only two of them.

![image](https://user-images.githubusercontent.com/42927786/96174968-27f55580-0ef8-11eb-9aed-b014d41bd81c.png)

**Comment by spadgett** [comment]
cc @serenamarie125 @alimobrem @christianvogt @beanh66

**Comment by beanh66** [comment]
Thanks, that's an interesting point @WillNilges! I cannot recall if that was considered when the perspectives were originally designed but I know @serenamarie125 and @beaumorley were looking into this switcher from a discoverability perspective so maybe they can weigh in on future plans. Adding @mceledonia here as well since he may have worked on some of the earlier visuals!

**Comment by beaumorley** [comment]
We have addressed discoverability of the perspective switcher for devs through a guided tour that starts on first time use. We do not have a plan to change the dropdown control at this time. However, one thing that is coming down the pipe is a third perspective for ACM. We are exploring options of using RBAC for perspectives and/or a no perspective UI. I suggest we close this issue based on this direction. Moving forward, we can ensure that this pain point (too many clicks) is considered in the future redesign. 

cc @andybraren

**Comment by christianvogt** [comment]
/close
based on suggestion from UX lead
