### ISSUE TITLE
Additional margin under nav section heading

### ISSUE THREAD

**Issue by spadgett** [openshift/console#710]
There's some additional margin between the section title and the items, for instance, between "Workloads" and "Pods below. (Current is on the left, previous on the right.)

Just checking if this is intentional or an oversight.

<img width="445" alt="overview okd 2018-10-26 17-33-22" src="https://user-images.githubusercontent.com/1167259/47593415-4ba6e600-d945-11e8-9f29-c760d212ea14.png">

cc @openshift/team-ux-review

**Comment by robszumski** [comment]
This seems intentional to make the hover state's padding look even, although it does produce a large gap that is not ideal.

I am hovering over Administration here, but you can't see the cursor:
![image](https://user-images.githubusercontent.com/755540/47595495-902a8580-d935-11e8-9558-fd01a063798a.png)

**Comment by serenamarie125** [comment]
@mshaks1996 can you take a look ?

**Comment by maryshak1996** [comment]
@spadgett yes this is intentional! @robszumski is spot on, that the intention is accommodate adequate padding around elements

**Comment by spadgett** [comment]
@maryshak1996 ok, thanks for the clarification!

/close
