### ISSUE TITLE
KubeVirt Web UI shows old Fedora / CentOS releases

### ISSUE THREAD

**Issue by sandrobonazzola** [openshift/console#7380]
OKD 4.6 is running on Fedora CoreOS 33 but KubeVirt Web UI is showing only fedora 29 - 31. All of them will be on end of life soon now that 33 is out. CentOS 6 is also past end of life.
Please refresh the list of operating systems in VM creation wizard.

**Comment by spadgett** [comment]
@jelkosz Do you know if this is still a problem?

**Comment by spadgett** [comment]
/uncc @jelkosz
/cc @yaacov 
/remove-lifecycle stale

@yaacov can you help?

**Comment by yaacov** [comment]
@spadgett hi, I think we can close this one:
This issue was addressed and the versions where updated:

p.s. We show in the UI what the versions available, a better place to submit such issues will be in https://github.com/kubevirt/common-templates

![screenshot-console-openshift-console apps ostest test metalkube org-2021 07 08-07_49_22](https://user-images.githubusercontent.com/2181522/124864147-1b9eb480-dfc1-11eb-88bc-168b85e03bc9.png)

**Comment by yaacov** [comment]
Note:
a - we show in console UI the templates available in the cluster, so if the cluster has old templates we will show the old OS versions
b - the latest templates are available from: https://github.com/kubevirt/common-templates#templates
c - older versions of OKD may bundle older versions of common-templates, AFAIK latest versions of kubevirt operator bundle the latest common-templates

**Comment by spadgett** [comment]
Thanks @yaacov. Closing based on your comments.
