### ISSUE TITLE
[FEATURE REQUEST] Navigation by label

### ISSUE THREAD

**Issue by delamart** [openshift/console#7592]
Currently I can navigate between different resource types and the views are always filtered by the same project via the top drop-down.
It would be very helpful if I could keep an active label filter between views. 
For example to view only resources for a given helm app for example between DEV/TEST/PROD namespaces.

**Comment by spadgett** [comment]
Hi, @delamart. What verison are you running?

This should be possible on the Home -> Search page. You can add a label selector and pick what resources you want to view. When you switch projects with the project selector, the label filter should be preserved. I believe this has been the behavior since 4.4.

https://www.openshift.com/blog/openshift-4.4-blog-search-page-changes
