### ISSUE TITLE
Update readme for running openshift with no authentication 

### ISSUE THREAD

**Issue by christiemolloy** [openshift/console#7861]
Hi there :) was running into some problems getting the console up and running today but spoke to @andrewballantyne and he helped me out. The process looked a little different to what is on the Readme under the section: "Openshift (no authentication)"

Just thought I'd leave the steps here and if you wanted to update the Readme slightly that might be helpful to others.

1. Find an available cluster (find a pinned message in #forum-ui-clusters)
2. Download the `kubeconfig` file and place it as `~/kubeconfig` in your home directory (on Mac to move it from downloads: `cp ~/Downloads/kubeconfig ~/kubeconfig`
3.  Run: `export KUBECONFIG=~/kubeconfig`
4. Run: `oc login -u kubeadmin -p <the-password-from-forum-ui>`
5. `source ./contrib/ooc-environment.sh`
6. `./bin/bridge`

**Comment by andrewballantyne** [comment]
@spadgett Our current instructions are a bit bizarre imo. 

[Our README](https://github.com/openshift/console/blob/master/README.md#openshift-no-authentication) specifies oddly to use the kubeadmin-password file from a cluster install?
> oc login -u kubeadmin -p $(cat /path/to/install-dir/auth/kubeadmin-password)

I think we can improve this to specify step 3, 4, 5, and 6 explicitly. 1 & 2 were part of our debugging and _probably_ can be omitted I think from the official README. Thoughts?

**Comment by spadgett** [comment]
I probably wouldn't recommend the steps above as written. It will change the kubeconfig file to be logged in as the `kubeadmin` user instead of using certificate auth for `system:admin`. I typically stash the kubeconfig file somewhere and don't touch it in case I ever need cluster admin on a cluster that has kubeadmin disabled, or need to debug a problem where the authentication operator is failing. It's better to run the `oc login` command from the README IMO. You might need to specify the API server URL, however.

```
$ oc login <api-server-url>
```

and manually entering `kubeadmin` and the password at the prompts should work.
