### ISSUE TITLE
Project display name and description unused 

### ISSUE THREAD

**Issue by cshinn** [openshift/console#802]
Unique names for projects are used in all places and display names only appear in the details, which seems to be the opposite of their intended purpose. Additionally, project descriptions don't appear anywhere that I've been able to find. I wonder if we should emphasize these fields more, or remove them if they are not used.

**Comment by spadgett** [comment]
Project display name has two big drawbacks:

1. It's not unique. Many projects can have the same display name.
2. It doesn't match what's used in the CLI or YAML, which causes confusion.

For these reasons, I like that we're starting to deemphasize them. They're hard to remove entirely since that's effectively an API change.

I do think descriptions are helpful and could be used more.
