### ISSUE TITLE
Support multiple links in consolenotification

### ISSUE THREAD

**Issue by patlachance** [openshift/console#8425]
We would like to display multiple links in a single consolenotification.
We can provide a PR is one can explain how we should start.
Thanks for good work!

**Comment by spadgett** [comment]
Hi, thanks for the issue. This one is a little more involved than a PR to the console repo since it would require an API change, probably deprecating the existing `link` property in favor of a `links` array. This would require API review and a few PRs to different repos to make the updates.

https://github.com/openshift/api/blob/a99ffa1cac6709edf8f502b16890b16f9a557e00/console/v1/types_console_notification.go#L25-L27

/kind feature
cc @alimobrem to see if we can consider this for a future release.
