### ISSUE TITLE
[Feature Request] Add "all" resources search by default for search tab

### ISSUE THREAD

**Issue by pumano** [openshift/console#8547]
**Description**
Currently we need manually add which resource we want to find and then search by label (see screenshot)
but it's counterproductive

<img width="600" src="https://user-images.githubusercontent.com/17675259/113456648-777ffd00-9416-11eb-940d-cab9e7ff909e.png">

**Expected result**
Looks like events tab do it perfectly by selecting "all" by default:

<img width="600" src="https://user-images.githubusercontent.com/17675259/113457245-fb86b480-9417-11eb-8567-3b525fe58390.png">

Please bring that user experience to search tab to developer and administrative perspective.

**Comment by spadgett** [comment]
Hi, unfortunately there's no API in Kubernetes to watch multiple resource kinds. We'd need to open a separate WebSocket for each resource kind, which is dozens or even hundreds depending on the number of CRDs in the cluster. This won't scale well, particularly when "All projects" is selected. Due to this limitation, we've decided that it's not feasible to let users watch all resource kinds on the Search page.

Events are different since we're watching one resource (events), and then filtering client-side on a property in the event for the observed object.
