### ISSUE TITLE
unable to install OKD console on ubunto 20.04 lte

### ISSUE THREAD

**Issue by leonicode** [openshift/console#8642]
Hi to all,
I'm trying to install for the first time the okd's console on my ubuntu 20.04 lte.
After a few minutes I ran ./build.sh, I see the following error message:

![okdInstallErr](https://user-images.githubusercontent.com/32000097/114604586-58e0f800-9c99-11eb-838d-7dc3afb837a7.png)

Node version is 14.16.1 and yarn version is 1.22.5.
Someone know what did I wrong ?
Thanks in advance
Leonard

**Comment by leonicode** [comment]
> 
> 
> Hi to all,
> I'm trying to install for the first time the okd's console on my ubuntu 20.04 lte.
> After a few minutes I ran ./build.sh, I see the following error message:
> 
> ![okdInstallErr](https://user-images.githubusercontent.com/32000097/114604586-58e0f800-9c99-11eb-838d-7dc3afb837a7.png)
> 
> Node version is 14.16.1 and yarn version is 1.22.5.
> Someone know what did I wrong ?
> Thanks in advance
> Leonard

Hi to all,
I resolved ... it was a memory problem: I increased my VM memory from 4GB to 8GB and all has nicely worked
Leonard

**Comment by spadgett** [comment]
Hi, thank you for reporting back. I had not seen this error, and it's good to know it's related to memory. We're working on splitting the console up so that it uses dynamic plugins for different components, which would lower the memory requirements and speed up builds for the core console. I'm going to close the issue since you have resolved it.

/close
