### ISSUE TITLE
Chrome crashes with out of memory exception

### ISSUE THREAD

**Issue by gkarthiks** [openshift/console#871]
We have the OpenShift Cluster with the OpenShift Console deployed. We have multiple namespaces and one of the namespace has around ~ 170 pods. 

When logged in, it's terrifically slow and hangs without any response. After a while the chrome window goes to the screen with `Aw snap, something went wrong while displaying this webpage` message.

If I have the `Developer Tools` opened, it automatically puts a break point and have a message as `Paused before potential out-of-memory crash` as shown below.

And the memory tab shows around 2Gi as shown in the next attachments.

<img width="853" alt="screen shot 2018-11-27 at 4 11 56 pm" src="https://user-images.githubusercontent.com/30545166/49120774-de97b080-f262-11e8-9407-1f5a9046fa91.png">

![screen shot 2018-11-27 at 4 37 08 pm](https://user-images.githubusercontent.com/30545166/49120813-09820480-f263-11e8-812d-b6488a683816.png)

Also attached the logs from the DevTools console logs.
[developertools.log](https://github.com/openshift/console/files/2622387/developertools.log)

**Comment by spadgett** [comment]
Thanks for the report. What version are you using and what page has the problem?

We've greatly improved performance in the next-gen console in OpenShift 4.0.

* Almost all tables in the UI now use virtual scrolling with react-virtualized, so that only items currently visible on the page are rendered.
* We've moved from AngularJS 1.x to React, which is more performant and only renders parts of the UI that have changed instead of the entire page on every update.

There is a developer preview at https://try.openshift.com/ if you want to try.

If you are running 3.11, it is also possible to deploy the 4.0 console in a separate namespace to check if you still see problems in this specific project.

**Comment by spadgett** [comment]
> That's an awesome news. But as of now I am running with 3.9, can I still deploy the v4 in a separate namespace?

I suspect the operator that manages the console will fail on 3.9, but I'm not certain. You could try

https://github.com/openshift/console-operator#running-against-a--400-cluster-min-311-recommended

cc @benjaminapetersen

**Comment by benjaminapetersen** [comment]
Yeah, it will probably not deploy on 3.9 at this point (and would demand the console live in `openshift-console` namespace).

**Comment by spadgett** [comment]
Closing for now since 3.9 is no longer supported and 4.x should perform much better. Let us know if you see similar issues in a 4.x console.

/close
