### ISSUE TITLE
The field status.members is invalid on Couchbase operator

### ISSUE THREAD

**Issue by crawford** [openshift/console#922]
Looking at https://console-openshift-console.apps.crawford.coreservices.team.coreos.systems/k8s/ns/default/clusterserviceversions/couchbase-operator.v1.0.0/couchbase.com~v1~CouchbaseCluster/cb-example, I see the following error:

![image](https://user-images.githubusercontent.com/368848/49677005-443d2700-fa31-11e8-94e5-86759b2df059.png)

**Comment by alecmerdler** [comment]
This is a known issue, @robszumski sent an email to the Couchbase Operator team to have them make some requested updates to their CRD schema which should fix it. @crawford Can you post the contents of the "YAML" tab for the `CouchbaseCluster` object?

**Comment by kevchu3** [comment]
@alecmerdler I'm getting the exact same error when I try to deploy a CouchbaseCluster with couchbase-operator.v1.1.0.  Here's the YAML for my `CouchbaseCluster` object.  I've taken all of the YAML default values supplied by the operator.

```
apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  creationTimestamp: 2019-04-24T15:42:36Z
  generation: 1
  name: cb-example
  namespace: kevin-sandbox
  resourceVersion: "83801"
  selfLink: /apis/couchbase.com/v1/namespaces/kevin-sandbox/couchbaseclusters/cb-example
  uid: 95923e80-66a7-11e9-8031-066848c6d666
spec:
  authSecret: cb-example-auth
  baseImage: registry.connect.redhat.com/couchbase/server
  buckets:
  - conflictResolution: seqno
    enableFlush: true
    evictionPolicy: fullEviction
    ioPriority: high
    memoryQuota: 128
    name: default
    replicas: 1
    type: couchbase
  cluster:
    analyticsServiceMemoryQuota: 1024
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
    autoFailoverTimeout: 120
    clusterName: cb-example
    dataServiceMemoryQuota: 256
    eventingServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    indexStorageSetting: memory_optimized
    searchServiceMemoryQuota: 256
  servers:
  - name: all_services
    services:
    - data
    - index
    - query
    - search
    - eventing
    - analytics
    size: 3
  version: 5.5.2-1
```

I also tailed the logs (`oc logs -f couchbase-operator-ff85f5954-nvtq7`) from the couchbase-operator pod and found this error, so I created the cb-example-auth secret in the kevin-sandbox namespace to remediate that error.
```
time="2019-04-24T15:26:10Z" level=info msg="Watching new cluster" cluster-name=cb-example module=cluster
time="2019-04-24T15:26:10Z" level=info msg="Janitor process starting" cluster-name=cb-example module=cluster
time="2019-04-24T15:26:10Z" level=error msg="Cluster setup failed: secrets \"cb-example-auth\" not found" cluster-name=cb-example module=cluster
time="2019-04-24T15:26:10Z" level=warning msg="Fail to handle event: ignore failed cluster (cb-example). Please delete its CR"
time="2019-04-24T15:26:23Z" level=info msg="Object (openshift-operators/cb-example) is deleted"
```

I then deleted and redeployed the CouchbaseCluster but still encounter the same `The field status.members is invalid` error, so presumably the missing secret was not the issue.  One pain point is that this error appears rather generic as status.members is invalid because there are no Couchbase pods, but that almost goes without saying.  The real question is why there are no Couchbase pods spinning up, and unfortunately `oc get events` in the namespace shows nothing.

**Comment by kevchu3** [comment]
Linked to https://bugzilla.redhat.com/show_bug.cgi?id=1702751.

As an FYI, I'm still observing this issue for couchbase-operator.v1.1.0 in the most recent OpenShift 4.1.6.

**Comment by mrhillsman** [comment]
@alecmerdler @kevchu3 this should be closed yes? The operator can be installed and used even though the UI is not displaying the information a user expects due to how the operator is updating the status resource correct?

**Comment by kevchu3** [comment]
@mrhillsman yes, this issue can be closed out now, thanks for the explanation.
