### ISSUE TITLE
Firefox not trusts the certificate during a PVC creation 

### ISSUE THREAD

**Issue by leonicode** [openshift/console#9402]
Hi to all,
I installed with success openshift console upon k8s+kubevirt; if I try to make a PVC using
the browser (from a remote pc - out of the k8s cluster -) it shows the following error:

<< It seems that your browser does not trust the certificate of the upload proxy. Please approve this certificate and try again>>

after I clicked the "Upload" botton to Upload Data to Persistent Volume Claim.
Why ? How can I to resolve this certificate problem ?
(If I click on the link "approve this certificate" the browser redirects to "https://undefined" ...)
Thanks in advance
Leonard

**Comment by yaacov** [comment]
@glekner hi, PTAL

**Comment by yaacov** [comment]
cc:// @matthewcarleton we know about this issue and the best we could do is provide the "approve cert" link, do you know of a PF pattern for "missing certificate" issue (maybe a cert download link ?)

**Comment by spadgett** [comment]
@yaacov Can you explain in what circumstances the certificate is not trusted?

We shouldn't encourage users to accept untrusted certificates, and I don't think it's a good pattern to add to PatternFly.

**Comment by glekner** [comment]
@leonicode you need to click the link, approve the certificate and then try to upload again.
@spadgett there will be cases where a cluster is installed and used with HTTPS with un-trusted certificates
@jelkosz can you elaborate on the certs

**Comment by spadgett** [comment]
> @spadgett there will be cases where a cluster is installed and used with HTTPS with un-trusted certificates

Can you give a specific example?

I'd expect all certificates to be trusted on a production cluster.

**Comment by spadgett** [comment]
I'm not familiar with how the feature is implemented. Is the backend proxying to a service, or is the frontend talking directly to a different route?

**Comment by leonicode** [comment]
@glekner if I click the link the browser redirects me on https://undefined i.e. on a void page ... it not works

**Comment by yaacov** [comment]
Hi all,

The kubevirt-plugin allows the use of an upload proxy deployed by CDI:
https://github.com/kubevirt/containerized-data-importer/blob/3c192b42b50ace878083c2c581343af73f1f10c6/doc/cdi-config.md

The upload proxy allow users to upload data directly from local machines into the cluster.

The upload proxy path is not proxied by the bridge 
https://github.com/openshift/console/blob/master/cmd/bridge/main.go

we can proxy the upload-proxy via the bridge, so it will use the same cert as the bridge ?
we can make a better UX design explaining why the proxy requires a cert, and allow to download it via a trusted url (e.g. the console)

@spadgett do you think we can add the upload-proxy to the bridge proxied sites ?
@matthewcarleton suggesting users to download certs is not that uncommon, for example: https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.0/html/rhevm_shell_guide/attaining_an_ssl_certificate_from_rhevm_for_a_rest_api_client

**Comment by yaacov** [comment]
p.s.

> I'd expect all certificates to be trusted on a production cluster.

@leonicode @spadgett , On production clusters system admins make sure all trusted urls have the certs installed correctly, this issue will only happen if the system admin forgot to set the trusted CA for the upload proxy.

**Comment by leonicode** [comment]
Hi yaacov, how can I do to set the trusted CA for the upload proxy ?
I need clear steps to verify because I'm not so expert in kubernetes ... I googled a bit but I not found clear example
Thanks in advance

**Comment by matthewcarleton** [comment]
> cc:// @matthewcarleton we know about this issue and the best we could do is provide the "approve cert" link, do you know of a PF pattern for "missing certificate" issue (maybe a cert download link ?)

I think we could just use the empty state from PatternFly. Not sure about the content but something like this. We could also check with the rest of the console to see if they have anything similar. 
<img width="534" alt="Screen Shot 2021-07-09 at 9 20 35 AM" src="https://user-images.githubusercontent.com/287880/125076949-ed8ba400-e096-11eb-86e9-e9d632e697a1.png">

**Comment by spadgett** [comment]
> @spadgett do you think we can add the upload-proxy to the bridge proxied sites ?

Probably the best way is to proxy from the console backend directly to the service if it uses OpenShift service serving certificates. Then the console will have the right CA file for the service and it avoids this issue altogether.

https://docs.openshift.com/container-platform/4.7/security/certificates/service-serving-certificate.html

This will be problematic when we implement multi-cluster, however, since console won't necessarily be running on the target cluster. It also needs https://issues.redhat.com/browse/CONSOLE-2892 since we're moving kubevirt to a dynamic plugin.

I would not encourage users toaccept untrusted certificates. It would be better to simply document this limitation and ask admins to set up the certs.

**Comment by yaacov** [comment]
> I installed with success openshift console upon k8s+kubevirt;

@leonicode hi, I missed some important data here, I thought you installed [openshift](https://www.okd.io/)+[HCO](https://github.com/kubevirt/hyperconverged-cluster-operator)

Some questions about you environment:
a - you are running vanilla k8s, not openshift (https://www.okd.io/) ?
b - you only installed kubvirt, not HCO (https://github.com/kubevirt/hyperconverged-cluster-operator) ?

I think the bug is that we assume CDI (https://github.com/kubevirt/containerized-data-importer) is installed, while in
vanille k8s+kubevirt it is not, so the error @leonicode is getting is wrong, the real issue is that he does not have CDI installed.

As a fix to this issue:
IIUC and @leonicode is using vanilla install:
@glekner can you fix the error msg when the UI can't upload a file (or check for CDI installed ?) ?

p.s.
@matthewcarleton looking at your design it is very similar to what @glekner have, I thought the issue was about it ...
But IIUC @leonicode problem is that CDI (https://github.com/kubevirt/containerized-data-importer) is not installed, and not just missing credentials.

so @glekner @matthewcarleton to solve this issue in a bigger scale we need to disable features that depend on HCO specific install, when a user install vanilla kubevirt on vanilla k8s they are missing lots of feature we expose by default, and we need to have better gating for them:

a. template list - not available on vanila k8s (openshift adds templates)
b. vm create wizard - not available (requires SSP operator)
c. file import from url, upload, copy - not available (requires CDI operator)
d. other things ... ?

**Comment by leonicode** [comment]
Hi yaacov,
yes I installed first vanilla k8s by Kubespray and then I installed openshift console following the steps in

https://kubevirt.io/2020/OKD-web-console-install.html 

Finally I deployed kubevirt using the Hyperconverged Cluster Operator (HCO)

**Comment by yaacov** [comment]
@leonicode hi, can you check what deployments are running in your cluster, by running:
`kubectl get deployments --all-namespaces | grep kubevirt`
`kubectl get deployments --all-namespaces | grep cdi`
`kubectl get pods --all-namespaces | grep cdi-uploadproxy`
`kubectl get routes --all-namespaces | grep cdi-uploadproxy`
?

HCO should have installed CDI and things should have worked (if no admin installed the certs, you will be prompt to add them, but it should work)

**Comment by yaacov** [comment]
Ahhh, `routes` are also an `openshift only` thing ... the CDI uploader can't use routes in vanilla k8s ... hmm ... I don't think we can support upload of files in vanila k8s , we use routes to auto-find it, can we expose the uploader in vanilla k8s ?...

**Comment by yaacov** [comment]
@dankenigsberg @fabiand  hi, did you know - https://kubevirt.io/2020/OKD-web-console-install.html ?
( we don't test / dev much with vanilla k8s ... )

**Comment by dankenigsberg** [comment]
Yes, I recall that blog spot. It's for the community to maintain.

**Comment by leonicode** [comment]
@yaacov see below (no routes ...)

![deployments](https://user-images.githubusercontent.com/32000097/125109110-3701e080-e0e3-11eb-9780-3c811ec3eb76.jpg)

![other](https://user-images.githubusercontent.com/32000097/125109124-3a956780-e0e3-11eb-8dd9-25e196358406.jpg)

**Comment by yaacov** [comment]
@spadgett @leonicode hi, I don't see us supporting file uploads on vanilla k8s any time soon,
the fix will be to remove un-supported options when vanilla k8s is detected.
cc:// @glekner

**Comment by leonicode** [comment]
**@yaacov** What should I do with my cluster ?
Must I remove bridge + vanilla k8s and, then, install openshift (https://www.okd.io/) + openshift-console ?
Can you give me some suggestions ?
