### ISSUE TITLE
Dynamic UI for operator - conditional form view fields

### ISSUE THREAD

**Issue by rasapala** [openshift/console#9592]
I was following the Declarative UI blog - https://www.openshift.com/blog/openshift-4-2-declarative-dynamic-ui-for-your-operator - and I have a question how can I additionally organize the UI fields defined in CRD scheme in the "form view" UI of my operator.

One form of manipulation I am interested in is how to organize certain fields in sections with headers - is there a way to do that ?

Another form is to introduce conditions if certain fields are set (input or x-descriptor selection) can I hide other fields or mark them as required/unrequired in a dynamic manner described in the blog.

apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion plus kind: CustomResourceDefinition

**Comment by spadgett** [comment]
cc @TheRealJon @tlwu2013

**Comment by rasapala** [comment]
A link to description or documentation where I can find some description would be a nice start.

**Comment by TheRealJon** [comment]
@rasapala Here is a link to a general readme on OLM descriptors: https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/README.md

And here is a further breakdown of the available x-descriptors and their use: https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md

The blog you referenced probably has some outdated information since it's referencing version 4.2. But generally speaking most of the features there should be covered in the current release. To answer the two specific questions:

**Organizing Fields in Sections**
We don't support arbitrary grouping. Instead, grouping is done according to the schema. Object and Array type properties will appear grouped under a collapsible header, and nesting of multiple objects or arrays is supported.

**Field Dependency**
This is supported. See the [fieldDependency](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#20-fielddependency) documentation.

**Comment by rasapala** [comment]
Hi, I am trying to use fieldDependency in the CSV setup. But it looks like it does not have any affect on the UI Form view. While I toggle the  model_config.enabled it has no effect on the coresponding fields. The fields do not hide nor become activated/deactivated. Please let me know if I am missing anything.

Below is part of the CSV definition:
`specDescriptors:
          - description: Set true to enable model configuration from config file.
            displayName: Use Model Config File
            path: model_config.enabled
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:booleanSwitch'
          - description: Path to model config file
            displayName: Model Config File
            path: model_config.config_configmap_name
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:fieldDependency:model_config.enabled:true'
              - 'urn:alm:descriptor:io.kubernetes:text'
          - description: Fill model settings if model config is not used
            displayName: Model Settings
            path: model_settings
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:fieldDependency:model_config.enabled:false'`

And the coresponding CRD part for this is
` spec:
              description: Spec defines the desired state of Ovms
              type: object
              required:
                - image_name
              properties:
                image_name:
                  description: Model Server docker image to be used
                  type: string
                  default: >-
                    registry.connect.redhat.com/intel/openvino-model-server:latest
                model_config:
                  description: Predefined config to be used by Model Server
                  type: object
                  properties:
                    config_configmap_name:
                      type: string
                    enabled:
                      type: boolean
                      default: false
                model_settings:
                  description: Fill model settings if model config is not used
                  type: object
                  properties:
                    model_name:
                      description: Name of the model loaded to Model Server
                      type: string
                      default: resnet
                    shape:
                      description: >-
                        Resets models shape (model must support reshaping). If
                        set, batch_size parameter is ignored
                      type: string
                    nireq:
                      description: Size of inference request queue for model executions
                      type: integer
                      format: int32`

**Comment by rasapala** [comment]
Issue fixed with fixing CRD and CSV.
